### DISCUSSION TITLE
Self Hosting on Raspberry Pi Issue

### DISCUSSION THREAD

**Discussion by Shazem8** [Viren070/AIOStreams#65] [Help] [answered]
Managed to install the add-on from source on Raspberry Pi. Opened the configuration using http://localhost:3000/configure
Then I copy the URL in the bottom of the page to install the add-on in Stremio but Stremio gives me this error:
failed to get add-on manifest from [URL.manifest.json] failed to fetch. load failed 
How can i fix this? @Viren070

**Comment by Viren070** [comment, marked as answer]
You need HTTPS to install the addon on Stremio unless accessing on the same device it's being hosted on.

**Reply by Shazem8** [reply]
What's the recommended way to do that?

**Reply by Viren070** [reply]
> What's the recommended way to do that?

@Shazem8 You can put it behind a reverse proxy such as Traefik, and use a free domain from Afraid or DuckDNS

**Reply by anil-sezer** [reply]
Hey @Viren070 , thanks for the app! Could you add a log to the system about this requirement? We hit a brick wall two days until we saw this post. I would love to add it and push a PR but I got 0 knowledge about typescript. But I can help with the Docker aspect of it if you want.

**Reply by Viren070** [reply]
A log indicating that HTTPS is required to install the addon on other devices? 

That is standard for every Stremio addon, I can add a note in the self hosting docs, but it wouldn't make sense to add it to the logs of the addon. 

I'm planning to rewrite that section of the docs with a guide on using Traefik and docker.

**Reply by anil-sezer** [reply]
Thanks for the reply @Viren070 !
The specific thing is this: I installed AIOStreams as a single container via Docker to a Raspberry Pi server, to test it with Streamio. When I tried to generate manifest url everything looks smooth:


![image](https://github.com/user-attachments/assets/878928e0-f51a-4772-bd33-e99ecd370a55)


---

### But when I try to copy this happens:
![image](https://github.com/user-attachments/assets/5180835a-c3f9-4455-bb30-bd46e509076c)

---

### And when I try to use Streamio or Streamio Web options:
 
![image](https://github.com/user-attachments/assets/b491f873-b0b6-4d47-a5a0-4f76f4a69ec9)

Since I'm new to the entire streamio thing, I checked Docker for logs when I got the copy error but found nothing.
Then tried to dig into code but my React experience is too low for that.

At the end, for verifying if the error is because of the HTTPS, I deployed your app into my Kubernetes cluster with these files:

``` yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiostreams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiostreams
  template:
    metadata:
      labels:
        app: aiostreams
    spec:
      containers:
        - name: aiostreams
          image: viren070/aiostreams:latest
          ports:
            - containerPort: 3000
          env:
            - name: ADDON_NAME
              value: "aiostreams"
            - name: ADDON_ID
              value: "aiostreams.viren070.com"
            - name: PORT
              value: "3000"
```


``` yaml
---
apiVersion: v1
kind: Service
metadata:
  name: aiostreams-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: aiostreams
```


``` yaml

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiostreams
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Or use letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - anilsteststream.duckdns.org
    secretName: anilsteststream-tls  # Cert will be stored here
  rules:
    - host: anilsteststream.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aiostreams-svc
                port:
                  number: 3000
```
