### DISCUSSION TITLE
Torrentio self host docker failed to fetch

### DISCUSSION THREAD

**Discussion by privatepenguinzero** [Viren070/AIOStreams#91] [Help] [answered]
I self hosted AIOstreams on my server using docker. I am proxying everything through Mediaflow (always self hosted) to share the same Debrid subscription without getting bans. 
Everything is forwarded through Cloudflare Tunnels.
Unfortunately when I search movies or series in stremio every addon in AIOstreams works fine (Mediafusion, Comet and Jackettio) but at the end of the list of available streams I get "Torrentio failed to fetch". Why? I supposed that self hosting makes Torrentio work instead of ElfHosted.

**Comment by Viren070** [comment]
run a curl request to https://torrentio.strem.fun/manifest.json from your server and see if it runs fine. 

Also, send the logs, it should have the full error.

**Reply by privatepenguinzero** [reply]
Curl runs OK as per screenshot:
![curl](https://github.com/user-attachments/assets/e8d1de2f-e00d-46be-b1de-93d6b8b259d6)

the log is:

```
|DBG| server > GET /B-eNpVUeta20YQ%2FfomUdN2rILBCQQI9IISU%2BPYBMeGUAfcdC2v4sW6VRdCetmRLIPt15on67dalya%2FZs6Z2bNnZirg%2BwaAZMZlBYZo4wg5OlSYA%2FlBUWMUeI0TdCn3aO4rKsAQ%2F8AIY7zBBFO8pfysR%2FnZS8qtsuuF6nqJday%2FxV%2Bwgce4VcdXaDVL2baqnuBrrNexg2%2Bwiz08w3N8ixdl%2FVdV7%2BM7PMImtvAUGUOP5myoeGZTQfeMI3OQfSjzMeVMUM6uKYd9yg8pf0z5NzSj%2B29p%2FhvN5HfGJTQT5grmw0B%2Bb1xCN41jjf4yoFYD%2BY8OVR1%2B1OE9zeQaFbKioanD3zpcGnB1BXJgVOCAinXDgHGShPH%2B5qbnhBvC5n4gog078EBegQE3e4fR02e7Iciv1bZ%2F0CI%2FlcGUP6vRxMiAJIgi7iciALlpVGjh8ZFgThqLwKepdMUN73EW2eNeEnHmxVTQwg48ntCUFtfMnvAkEQFNZZr%2B7%2BeB%2F8IVLULOI8cVt%2BVXUK1SIeNx8LHztPOgbpoDuaG8rYMBXc7cR3U%2BjMQIpDIbceaOSkx33Ua9fd7bPqpvWSe7zVcn3f67Vqdp9RvtN%2Bcty2pfHLcuGi%2BsTr%2Fd3D3ut3uNk9cW0NJyv5Rk7n%2BKWSfinkg98SfXJdiHfcp086O28Cea1u2u8CeUnQXRMLjVfFLmdLf9%2FEltz7b3qjvMcarbfGenOnwyqlUZe%2B7U7Gc1vjWsAS1PHcd2g3RlI1ghysI02VDXUGyYquVmRyz%2B5POPsSb5Cmn%2B81lU5WEYMemwleNQTEI2oazH%2BSjSVKxSyk4jEfgrBzr9nWZy3aiY5sBEKsz1ClD2wNKScpqV5FQfcW3t86sAFQYcHgDNDHh8AHSnXhbqJbBQtPgnA%2BheMrXEEZQyc5qZA0kLUyFlg5Zlqs7%2FFS1pQXO6pzuaUUFTyinD9%2F8CI1SR6Q%3D%3D/stream/movie/tt5040012.json
|DBG| server > Extracting base64 encoded and compressed config
|DBG| server > Extracted config for stream request
|DBG| server > Successfully removed or decrypted sensitive info
|DBG| server > Requesting streams for movie tt5040012
|DBG| mediaflow > getMediaFlowPublicIp > GET /proxy/ip?api_password=***
|DBG| wrappers > base > Torrentio: Making a proxied request to https://torrentio.strem.fun/<redacted>/stream/movie/tt5040012.json with user IP <redacted>
|DBG| wrappers > mediafusion: Returning cached config string
|DBG| wrappers > base > Comet: Making a proxied request to https://comet.elfhosted.com/<redacted>/stream/movie/tt5040012.json with user IP <redacted>
|DBG| wrappers > base > Jackettio: Making a proxied request to https://jackettio.elfhosted.com//stream/movie/tt5040012.json with user IP <redacted>
useMultipleInstances=true useMultipleInstances=true showP2PStreams=true
|DBG| wrappers > peerflix: Found 2 usable services: realdebrid, torbox
|DBG| wrappers > base > Peerflix: Making a proxied request to https://peerflix-addon.onrender.com/<redacted>/stream/movie/tt5040012.json with user IP <redacted>
|DBG| wrappers > base > MediaFusion: Making a proxied request to https://mediafusion.elfhosted.com/<redacted>/stream/movie/tt5040012.json with user IP <redacted>
|ERR| wrappers > base > Torrentio: fetch failed
TypeError: fetch failed
    at fetch (/app/node_modules/undici/index.js:120:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Torrentio.getStreams (/app/packages/wrappers/dist/base.js:135:30)
    at async Torrentio.getParsedStreams (/app/packages/wrappers/dist/base.js:25:25)
    at async getTorrentioStreams (/app/packages/wrappers/dist/torrentio.js:71:16)
    at async AIOStreams.getStreamsFromAddon (/app/packages/addon/dist/addon.js:647:24)
    at async /app/packages/addon/dist/addon.js:619:55
    at async Promise.all (index 0)
    at async AIOStreams.getParsedStreams (/app/packages/addon/dist/addon.js:638:9)
    at async AIOStreams.getStreams (/app/packages/addon/dist/addon.js:52:49) {
  [cause]: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:216:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
|ERR| addon > getParsedStreams: Failed to get streams from Torrentio: fetch failed
|INF| addon > getParsedStreams: Got 1 streams from addon Jackettio in 353.00ms
|INF| addon > getParsedStreams: Got 21 streams from addon Comet in 638.00ms
|INF| addon > getParsedStreams: Got 234 streams from addon MediaFusion in 961.00ms
|INF| addon > getParsedStreams: Got 11 streams from addon Peerflix in 1.02s
|INF| addon > getStreams: Got 267 parsed streams and 1 error streams in 2.33s
|INF| addon > getStreams: Initial filter to 143 streams in 3.00ms
|INF| addon > cleaner: Received 143 streams to clean
|INF| addon > cleaner: Found 107 unique filenames
|INF| addon > cleaner: Deduplicated streams by filename to 116 streams in 4.00ms
|INF| addon > cleaner: Found 99 unique hashes with 15 streams not grouped
|INF| addon > cleaner: Deduplicated streams by hash to 99 streams in 7.00ms
|INF| addon > cleaner: Deduplicated streams to 114 streams in 12.00ms
|INF| addon > getStreams: Sorted results in 10.00ms
|INF| addon > getStreams: Created 115 stream objects in 43.00ms
|INF| addon > getStreams: Total time taken to serve streams: 2.40s
```

**Reply by Viren070** [reply]
You're using a proxy? What proxy are you using?

**Reply by privatepenguinzero** [reply]
I am running mediaflow proxy. Is it wrong?

**Reply by Viren070** [reply]
No, the `ADDON_PROXY` env var, what is that set to. The logs say it is making a proxied request. 

You only use `ADDON_PROXY` to get around blocks.

**Comment by privatepenguinzero** [comment]
I tried using:
```
TRANSPORT_ROUTES: '{ "https://torrentio.strem.fun": { "proxy": true }, "https://mediafusion.elfhosted.com": { "proxy": true }, "https://api.real-debrid.com": { "proxy": true } }'
```
Didnt work..
```      
ALL_PROXY: true
```
Didn't work..
```  
TRANSPORT_ROUTES: '{ "https://torrentio.strem.fun": { "proxy": true } }'
```
Didn't work..

Docker compose
```
services:
 mediaflow-proxy:
    ports:
      - 8888:8888
    environment:
      API_PASSWORD: ${API_PASSWORD}
      PROXY_URL: http://warp:1080
      SECRET_KEY: ${SECRET_KEY}
      TRANSPORT_ROUTES: '{ "https://torrentio.strem.fun": { "proxy": true },
        "https://mediafusion.elfhosted.com": { "proxy": true },
        "https://api.real-debrid.com": { "proxy": true } }'
      #ALL_PROXY: true
      #TRANSPORT_ROUTES: '{ "https://torrentio.strem.fun": { "proxy": true } }'
    image: mhdzumair/mediaflow-proxy:latest
    hostname: mediaflow-proxy
    container_name: mediaflow-proxy
    networks:
      - frontend
    restart: unless-stopped
 
 warp:
    image: monius/docker-warp-socks:v3
    container_name: warp
    hostname: warp
    restart: unless-stopped
    ports:
      - 1080:1080
    environment:
      - NET_PORT=1080
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - frontend
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - warp-data:/lib/modules
    healthcheck:
      test: curl -x "socks5h://127.0.0.1:1080" -fsSL
        "https://www.cloudflare.com/cdn-cgi/trace" | grep -qE "warp=(plus|on)"
        || exit 1
      interval: 15s
      timeout: 5s
      retries: 3

 aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    hostname: aiostreams
    restart: unless-stopped
    ports:
      - 2080:3000
    environment:
      ADDON_PROXY: http://warp:1080
    networks:
      - frontend

volumes:
  warp-data: null
networks:
  frontend:
    external: true
```
