### ISSUE TITLE
bug: Cannot stream using external player when using Mediaflow Proxy

### ISSUE THREAD

**Issue by zaylman** [Viren070/AIOStreams#127]
### Deployment Method

VPS

### Addon Version

v1.14.2

### Bug Area

Playback

### Device/Browser/OS/Stremio Version

iOS/iPadOS/TVOS on Vidi version 1.8.0 and Infuse 8.1.3

### Bug Description / Steps to Reproduce

AIO Streams using Mediaflow proxy works just fine for the internal player in Vidi (KSPlayer) for all streams including TorrentIO. I do not believe this is a TorrentIO/VPS proxy issue (but I'd be happy to be wrong) so I didn't update the other ticket issue so as to not muddy the waters for that work around. The issue only occurs when trying to use an external player like Infuse or VLC.

When using Infuse as an external player I get "An error occured. Failed to open input stream in the demuxing stream"

In Mediaflow proxy it looks like a connection was made but the stream link wasn't included:

`172.18.0.2:36236 - "GET /proxy/stream?api_password=XXXX HTTP/1.1" 422` is all that's in the log when trying to play through Infuse.

I'm using docker with AIOStreams, Mediaflow Proxy and Warp

```
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    networks:
      stremio: {}
    environment:
      - SECRET_KEY=${AIOSTREAMS_SECRET_KEY}
      - ADDON_NAME=Streamit
      - DETERMINISTIC_ADDON_ID=true
      - ADDON_PROXY=${ADDON_PROXY}
    depends_on:
      - traefik
      - pocket-id
      - warp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aio.rule=Host('${AIOSTREAMS_HOST}')"
      - "traefik.http.routers.aio.service=aio@docker"
      - "traefik.http.routers.aio.tls=true"
      - "traefik.http.services.aio.loadbalancer.server.port=3000"
      - "traefik.http.routers.aio.entrypoints=websecure"
      - "traefik.http.routers.aio.tls.certresolver=myresolver"
      - "traefik.http.routers.aio.middlewares=aio-auth@file"

 mediaflow-proxy:
    image: mhdzumair/mediaflow-proxy
    container_name: mediaflow-proxy
    restart: unless-stopped
    networks:
      stremio: {}
    environment:
      API_PASSWORD: ${MEDIAFLOW_API_PASSWORD}
      PROXY_URL: ${ADDON_PROXY}
      TRANSPORT_ROUTES: '{ "https://torrentio.strem.fun": { "proxy": true } }'
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediaflow.rule=Host('${MEDIAFLOW_HOST}')"
      - "traefik.http.routers.mediaflow.service=mediaflow@docker"
      - "traefik.http.routers.mediaflow.tls=true"
      - "traefik.http.services.mediaflow.loadbalancer.server.port=8888"
      - "traefik.http.routers.mediaflow.entrypoints=websecure"
      - "traefik.http.routers.mediaflow.tls.certresolver=myresolver"
      - "traefik.http.routers.mediaflow.middlewares=mediaflow-auth@file"

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 10:200 rwm'
    expose:
      - 1080
    networks:
      stremio: {}
    environment:
      - WARP_SLEEP=2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /root/appdata/warp:/var/lib/cloudflare-warp
```

Looking at the Mediaflow Proxy github page it looks like there is a section specifically about URL encoding for VLC player. I'm wondering if this is related?

![Image](https://github.com/user-attachments/assets/eefbe889-c02c-4e28-952f-7bb632b33e58)

Another way I tested was using stremio web with an external player. Unfortunately, it doesn't have Infuse as an option but I was able to test VLC and Outplayer. VLC did not work like I suspected but much to my surprise, Outplayer did. Curiously, when using Outplayer as an external player in Vidi it did NOT work.

### Expected Behavior

The stream would start in Infuse or VLC

### Debugging Checklist

- [ ] If applicable, I have included server logs 
- [ ] If applicable, I have included MediaFlow logs

### Issue Checklist

- [x] I have written a short but informative title that clearly describes the issue.
- [x] I have given clear and descriptive steps to reproduce the issue.
- [x] I have checked open and closed issues and confirmed that this is not a duplicate of another issue.
- [x] I have filled out all of the requested information adequately. 
- [x] I am using the [latest version](https://github.com/Viren070/AIOStreams/releases/latest).
