### ISSUE TITLE
bug: auto play not working when MediaFlow is enabled

### ISSUE THREAD

**Issue by DooSkagg** [Viren070/AIOStreams#13]
### My Issue
When playing something and the next episode attempts to autoplay it shows the logo for the media loading for a second then freezes and nothing autoplays and exits back to the medias homepage. Autoplay works fine with torrentio or stremthru so not sure if its something wrong with my config.

[Video of issue](https://github.com/user-attachments/assets/60e2840e-1331-41a3-92ef-462a48c593c3)

##### Docker
```yaml
services:
  aiostreams:
    container_name: aiostreams
    image: ghcr.io/viren070/aiostreams:latest
    ports:
      - 6980:3000
    environment:
      - ADDON_NAME=AIOStreams
      - ADDON_ID=aiostreams.fast.com
      - SECRET_KEY=[REDACTED]
      - EASYNEWS_PLUS_URL=[REDACTED]
      - COMET_URL=[REDACTED]
    restart: unless-stopped
    depends_on:
      - mediaflow-proxy
      - easynews
      - comet
  mediaflow-proxy:
    container_name: mediaflow-proxy
    image: mhdzumair/mediaflow-proxy
    ports:
      - 8888:8888
    environment:
      - API_PASSWORD=[REDACTED]
    restart: unless-stopped
```
#### AIOStreams
![image](https://github.com/user-attachments/assets/8bbd3ab4-038d-487c-8d66-c38b96502a2e)
