### ISSUE TITLE
bug: every day i need to reinstall

### ISSUE THREAD

**Issue by emaschi123** [Viren070/AIOStreams#84]
### Checklist

- [x] I have checked open and closed [issues](https://github.com/Viren070/AIOStreams/issues)

### Deployment Method

Private ElfHosted Instance

### Addon Version

1.13.7

### Bug Area

Using the addon

### Device/Browser/OS/Stremio Version

all the devices

### Bug Description / Steps to Reproduce

Hi, don't know if it's the vps, but everyday i need to reinstall the addon, it's crashing and i cant see streams, today mediafusion and torrentio shows 1500 timeout. i'm missing something in the configs? im using docker compose with warp.

### Expected Behavior

if an update came up the addon in the old version should work

### Debugging Checklist

- [ ] If applicable, I have included server logs 
- [ ] If applicable, I have included MediaFlow logs

**Comment by Viren070** [comment]
Please edit your issue with more details. 

What do you mean crashing? If you mean the addon actually crashes, then please show the logs. 

What do you mean mediafusion and torrentio show 1500 timeout? 

Why do you need to reinstall the addon everyday? What happens if you don't?

**Comment by mrpentest** [comment]
I had a similar experience at some point but I removed the warp proxy from my VPS docker installation, and the issues went away. So now I use it without the warp "vpn".

**Comment by Viren070** [comment]
You only need warp/gluetun if Torrentio is blocking requests from your VPS.

You can configure AIOStreams to only use the proxy for Torrentio as well with the `ADDON_PROXY_CONFIG` environment variable by setting it to the following: 

```
*:false,*.strem.fun:true
```

**Comment by emaschi123** [comment]
Sorry for the poor logs or evidence, but it's like [mrpentest](https://github.com/mrpentest) says, i'm on vps with warp and every day when i try to search something i've the red X and some timeout errors, next time i'll get a logs and a screenshot!

**Comment by Viren070** [comment]
You can try using a different warp image (you'll want to remove the old volume before switching)

```yaml
services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 10:200 rwm'
    expose:
      - 1080
    environment:
      - WARP_SLEEP=5
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data/warp:/var/lib/cloudflare-warp
    healthcheck:
      test: curl -x "socks5h://127.0.0.1:1080" -fsSL "https://www.cloudflare.com/cdn-cgi/trace" | grep -qE "warp=(plus|on)" || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
```

or switch to gluetun with Proton VPN and replace http://warp:1080 with http://gluetun:8888

(get your wireguard private key from https://account.proton.me/u/1/vpn/WireGuard) 

```yaml
services: 
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 127.0.0.1:8888:8888/tcp # HTTP proxy
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=YOUR_WIREGUARD_PRIVATE_KEY
      - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=true
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      - HTTPPROXY=on
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      - HTTPPROXY_STEALTH=on
    volumes:
      - ./data/gluetun:/gluetun
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 1m
```
